version: 0.2

env:
  variables:
    isTrue: "true"
phases:
  build:
    commands:
      - sbt package
artifacts:
  files:
    - 'scala_tut/target/scala-2.12/*.jar'
  name:
    hello_world_pkg-$(date +%Y-%m-%d %H:%M:%S)
  discard-paths:
    yes
